databases:
  - name: symfony-db
    plan: free

services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: AUTO_SEED
        value: "false"
      - key: APP_SECRET
        generateValue: true
      - key: AUTO_BASELINE
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString
      - key: TRUSTED_PROXIES
        value: "127.0.0.1,REMOTE_ADDR"
      - key: TRUSTED_HOSTS
        value: "^.+\\.onrender\\.com$"
