<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250923143009 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('DROP TABLE adresse');
        $this->addSql('DROP TABLE affaire');
        $this->addSql('DROP TABLE agence');
        $this->addSql('DROP TABLE agence_membre');
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP TABLE agent_equipe');
        $this->addSql('DROP TABLE agent_fonction');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE documents_repertoire');
        $this->addSql('DROP TABLE doe');
        $this->addSql('DROP TABLE equipe');
        $this->addSql('DROP TABLE fonction');
        $this->addSql('DROP TABLE formation');
        $this->addSql('DROP TABLE images');
        $this->addSql('DROP TABLE intervention');
        $this->addSql('DROP TABLE maintenance');
        $this->addSql('DROP TABLE passeport');
        $this->addSql('DROP TABLE rapport_maintenance');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE rendez_vous_image');
        $this->addSql('DROP TABLE rendu_intervention');
        $this->addSql('DROP TABLE rendu_intervention_image');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE site_affaire');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE adresse (id BIGINT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ligne1 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ligne2 VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, code_postal VARCHAR(40) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, ville VARCHAR(120) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, region VARCHAR(120) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, pays VARCHAR(120) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_adresse_ville_cp (ville, code_postal), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE affaire (id BIGINT AUTO_INCREMENT NOT NULL, nom_affaire VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, client_id BIGINT DEFAULT NULL, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX client_id (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE agence (id BIGINT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, designation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, adresse_id BIGINT DEFAULT NULL, telephone VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX adresse_id (adresse_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE agence_membre (id BIGINT AUTO_INCREMENT NOT NULL, agence_id BIGINT NOT NULL, agent_matricule VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, role VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'Membre\' COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX agence_id (agence_id, agent_matricule), INDEX agent_matricule (agent_matricule), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE agent (matricule VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, `admin` TINYINT(1) DEFAULT 0, email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, tel VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, actif TINYINT(1) DEFAULT 1, date_entree DATE DEFAULT NULL, commentaire TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, agence_id BIGINT NOT NULL, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX email (email), INDEX idx_agent_agence (agence_id), PRIMARY KEY(matricule)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE agent_equipe (id BIGINT AUTO_INCREMENT NOT NULL, equipe_id BIGINT NOT NULL, agent_matricule VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX equipe_id (equipe_id, agent_matricule), INDEX agent_matricule (agent_matricule), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE agent_fonction (id BIGINT AUTO_INCREMENT NOT NULL, agent_matricule VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, fonction_id BIGINT NOT NULL, principal TINYINT(1) DEFAULT 0, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX agent_matricule (agent_matricule, fonction_id), INDEX fonction_id (fonction_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE client (id BIGINT AUTO_INCREMENT NOT NULL, nom_client VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, representant_nom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, representant_email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, representant_tel VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, adresse_id BIGINT DEFAULT NULL, commentaire TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX adresse_id (adresse_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE documents_repertoire (id BIGINT AUTO_INCREMENT NOT NULL, cible_type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, cible_id BIGINT NOT NULL, nature VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'Document\' COLLATE `utf8mb4_unicode_ci`, nom_fichier VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, type_mime VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'application/octet-stream\' COLLATE `utf8mb4_unicode_ci`, taille_octets BIGINT DEFAULT NULL, chemin_fichier VARCHAR(1024) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, checksum_sha256 VARCHAR(64) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, auteur_matricule VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX auteur_matricule (auteur_matricule), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE doe (id BIGINT AUTO_INCREMENT NOT NULL, site_id BIGINT NOT NULL, affaire_id BIGINT NOT NULL, titre VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX site_id (site_id, affaire_id, titre), INDEX affaire_id (affaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE equipe (id BIGINT AUTO_INCREMENT NOT NULL, agence_id BIGINT NOT NULL, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_equipe_agence (agence_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE fonction (id BIGINT AUTO_INCREMENT NOT NULL, code VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX code (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE formation (id BIGINT AUTO_INCREMENT NOT NULL, agent_matricule VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, date_obtention DATE DEFAULT NULL, date_expiration DATE DEFAULT NULL, organisme VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, commentaire TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX agent_matricule (agent_matricule), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE images (id BIGINT AUTO_INCREMENT NOT NULL, nom_fichier VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, type_mime VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'image/jpeg\' COLLATE `utf8mb4_unicode_ci`, taille_octets BIGINT NOT NULL, image_blob LONGBLOB NOT NULL, commentaire_image TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, auteur_matricule VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX auteur_matricule (auteur_matricule), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE intervention (id BIGINT AUTO_INCREMENT NOT NULL, maintenance_id BIGINT NOT NULL, description TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATE NOT NULL, date_fin DATE DEFAULT NULL, intervention_precedente_id BIGINT DEFAULT NULL, date_debut_ts DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin_ts DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX maintenance_id (maintenance_id), INDEX intervention_precedente_id (intervention_precedente_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE maintenance (id BIGINT AUTO_INCREMENT NOT NULL, doe_id BIGINT NOT NULL, affaire_id BIGINT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, etat VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'Pas_commence\' COLLATE `utf8mb4_unicode_ci`, responsable VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX doe_id (doe_id), INDEX affaire_id (affaire_id), INDEX responsable (responsable), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE passeport (id BIGINT AUTO_INCREMENT NOT NULL, agent_matricule VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, permis TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, habilitations TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, certifications TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, commentaire TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX agent_matricule (agent_matricule), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rapport_maintenance (id BIGINT AUTO_INCREMENT NOT NULL, maintenance_id BIGINT NOT NULL, date_rapport DATETIME DEFAULT CURRENT_TIMESTAMP, matricule VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, nom_client VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, adresse_client_id BIGINT DEFAULT NULL, commentaire_interne TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, materiel_commander TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, etat VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'Pas_commence\' COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX maintenance_id (maintenance_id), INDEX matricule (matricule), INDEX adresse_client_id (adresse_client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rendez_vous (id BIGINT AUTO_INCREMENT NOT NULL, site_id BIGINT NOT NULL, intervention_id BIGINT DEFAULT NULL, sujet VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, date_rdv DATE NOT NULL, heure_rdv TIME DEFAULT NULL, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, statut VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'Planifie\' COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX site_id (site_id), INDEX intervention_id (intervention_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rendez_vous_image (id BIGINT AUTO_INCREMENT NOT NULL, rendez_vous_id BIGINT NOT NULL, image_id BIGINT NOT NULL, UNIQUE INDEX rendez_vous_id (rendez_vous_id, image_id), INDEX image_id (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rendu_intervention (id BIGINT AUTO_INCREMENT NOT NULL, intervention_id BIGINT NOT NULL, resume TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, valeur TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX intervention_id (intervention_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rendu_intervention_image (id BIGINT AUTO_INCREMENT NOT NULL, rendu_intervention_id BIGINT NOT NULL, image_id BIGINT NOT NULL, UNIQUE INDEX rendu_intervention_id (rendu_intervention_id, image_id), INDEX image_id (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE site (id BIGINT AUTO_INCREMENT NOT NULL, nom_site VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, adresse_id BIGINT DEFAULT NULL, commentaire TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX adresse_id (adresse_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE site_affaire (id BIGINT AUTO_INCREMENT NOT NULL, site_id BIGINT NOT NULL, affaire_id BIGINT NOT NULL, date_debut DATETIME DEFAULT CURRENT_TIMESTAMP, date_fin DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX site_id (site_id, affaire_id), INDEX affaire_id (affaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
